# Generated by Django 5.0.4 on 2024-04-23 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_alter_article_tags_alter_scope_article'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scope',
            options={'ordering': ['-is_main', 'tag']},
        ),
    ]
